version: '3'
services:
  mongodb:
    ports:
      - 27001:27017
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=taskit
      - MONGO_INITDB_ROOT_PASSWORD=taskit2023
