openapi: 3.0.2
info:
  title: "Taskit API"
  version: 0.2.0
paths:
  "/api/tasks/[id]":
    get:
      operationId: getTaskById
      responses:
        "200":
          description: return a task with provided id                     
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        category:
          type: string
        time:
          type: string
      required:
        - id
        - title
