on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

env:
  APP_NAME: taskit
  APP_DOMAIN: 'https://taskit-three.vercel.app'
  APP_PATH: './src/web'
  NODE_VERSION: '18.x'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: npm install, build, and test
      working-directory: ./src/web
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
