on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  APP_NAME: taskit
  APP_DOMAIN: 'https://taskit-three.vercel.app'
  APP_PATH: './src'
  NODE_VERSION: '18.x'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: taskit-app
        path: ./src/
        
    - name: npm install, build, and test
      working-directory: ./src
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present


  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ env.APP_DOMAIN }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: taskit-app
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}        

    - name: 'Deploy to Vercel'
      id: deploy-to-vercel
      run: |
        npm install -g vercel
        vercel -t ${{ secrets.VERCEL_TOKEN }} --name ${{ env.APP_NAME }} --yes
